# Name of the workflow
name: Fetch RecentPapers

# Trigger the workflow manually or every day at 00:00 UTC
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

# Define the jobs to run
jobs:
  update-papers:
    # Specify the runner environment
    runs-on: ubuntu-latest
    # Check out the repository code
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all history for all branches and tags
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Use the Python version you need
      - name: Install dependencies
        run: |
          pip install requests
          pip install Django==4.2.4
      - name: Update papers
        run: python manage.py update_papers.py
