# Name of the workflow
name: Fetch RecentPapers

# Trigger the workflow manually or every day at 00:00 UTC
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

# Define the jobs to run
jobs:
  update-papers:
    # Specify the runner environment
    runs-on: ubuntu-latest
    # Check out the repository code
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all history for all branches and tags
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Use the Python version you need
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests
          pip install arxiv==1.4.8
          pip install Django==4.2.4
          pip install numpy==1.25.2
          pip install pandas==2.0.3
          pip install pathlib==1.0.1
          pip install Pillow==10.0.0
          pip install psycopg2==2.9.7
          pip install psycopg2-binary==2.9.7
          pip install python-dotenv==1.0.0
          pip install regex
          pip install requests
          pip install  sentence-transformers==2.2.2
          pip install tqdm

      - name: Debug Environment Variables
        run: |
          echo "SQL_NAME: $SQL_NAME"
          echo "SQL_USER: $SQL_USER"
          echo "SQL_PASSWORD: $SQL_PASSWORD"
          echo "HOST: $HOST"
          echo "PORT: $PORT"
        
      - name: Update papers
        env:
          SECRET_KEY: ${{ secrets.PaperMate_db_SECRET_KEY }}
          SQL_NAME: ${{ secrets.PaperMate_db_SQL_NAME }}
          SQL_USER: ${{ secrets.PaperMate_db_SQL_USER }}
          SQL_PASSWORD: ${{ secrets.PaperMate_db_SQL_PASSWORD }}
          HOST: ${{ secrets.PaperMate_db_HOST }}
          PORT: ${{ secrets.PaperMate_db_PORT }}
        run: python manage.py update_papers

