# Name of the workflow
name: Fetch RecentPapers

# Trigger the workflow manually or every day at 00:00 UTC
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

# Define the jobs to run
jobs:
  update-papers:
    # Specify the runner environment
    runs-on: ubuntu-latest
    # Check out the repository code
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all history for all branches and tags
          fetch-depth: 0
      # Install the requirements from requirements.txt file
      - name: Install requirements
        run: pip install -r requirements.txt
      # Run the command without checking the branch name
      - name: Update papers
        run: python manage.py update_papers.py
