# Name of the workflow
name: Fetch RecentPapers

# Trigger the workflow every minute
on:
  schedule:
    - cron: '* * * * *'

# Define the jobs to run
jobs:
  update-papers:
    # Specify the runner environment
    runs-on: ubuntu-latest
    # Check out the repository code
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all history for all branches and tags
          fetch-depth: 0
      # Run the command without checking the branch name
      - name: Update papers
        run: python manage.py update_papers.py
